appointment/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.conf.urls import url
from django.http import HttpResponse

from doctors.views import *

urlpatterns = [
    path('', root_page),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', register),
    path('browse/', client_browse_view),
    path('my_appointments', my_appointments_view),
    path('profile/', profile_view),
    path('doctor/<int:doctor_id>/', doctor_timetable_view),
    path('welcome/', welcome_view),

    url(r'^robots.txt', lambda x: HttpResponse(
        'User-Agent: *\nDisallow:', content_type='text/plain'
        ), name='robots_file')
]

doctors/models.py
from django.db import models
from django.conf import settings

import datetime


class DoctorCategory(models.Model):
    name = models.CharField(max_length=127)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Doctor categories"


class Doctor(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    categories = models.ManyToManyField(DoctorCategory, blank=True)
    address = models.CharField(max_length=512, blank=True, default="")

    def __str__(self):
        return self.user.username


class Client(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Appointment(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True)
    datetime = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s: doctor %s, client %s" % (
            self.datetime.strftime("%Y-%m-%d"),
            self.doctor.user.username,
            self.client.user.username)

    class Meta:
        permissions = [("can_change_is_active", "Can (de)activate appointments")]


class Schedule(models.Model):
    doctor = models.OneToOneField(Doctor, on_delete=models.CASCADE)
    default_start = datetime.time(8, 0)
    default_end = datetime.time(16, 0)
    interval = models.PositiveSmallIntegerField(default=15)
    monday_from = models.TimeField(default=default_start)
    monday_to = models.TimeField(default=default_end)
    tuesday_from = models.TimeField(default=default_start)
    tuesday_to = models.TimeField(default=default_end)
    wednesday_from = models.TimeField(default=default_start)
    wednesday_to = models.TimeField(default=default_end)
    thursday_from = models.TimeField(default=default_start)
    thursday_to = models.TimeField(default=default_end)
    friday_from = models.TimeField(default=default_start)
    friday_to = models.TimeField(default=default_end)
    saturday_from = models.TimeField(default=default_start)
    saturday_to = models.TimeField(default=default_end)

    def __str__(self):
        return self.doctor.user.username

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'doctors/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />

    <link rel="shortcut icon" href="{% static 'doctors/favicon.ico' type='image/x-icon' %}">
    <title>APPointment</title>
  </head>
  <body>
	{% include 'header.html' %}
  {% include 'navbar.html' %}
  <div class="container-fluid min-vh-100">
  	{% block base %}

  	{% endblock base %}
  </div>
	{% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/base_container.html
{% extends 'base.html' %}

{% block base %}
<div class="container">
    {% block base_container %}
    {% endblock base_container %}
</div>
{% endblock base %}

templates/browse.html
{% extends 'base.html' %}

{% block base %}
	<div class="row">
		<div class="col-12 col-md-3">
			<h2>Categories</h2>
			<div class="list-group" id="list-tab" role="tablist">
				{% for category in categories %}
					<a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" data-toggle="list" href="#category_{{ category.pk }}" role="tab">
						{{ category.name }}
						<span class="badge badge-primary badge-pill">{{ category.doctor_set.count }}</span>
					</a>
				{% endfor %}
				{% if not categories %}
					<h3>No categories were added</h3>
				{% endif %}
			</div>
		</div>

		<div class="col-12 col-md-9">
			<h2>Doctors in this category</h2>
			<div class="tab-content">
				{% for category in categories %}
					<div class="tab-pane" id="category_{{ category.pk }}" role="tabpanel">
						{% for doctor in category.doctor_set.all %}
							<div class="card">
								<div class="card-body">
									<h4 class="card-title">{{ doctor.user.first_name }} {{ doctor.user.last_name }}</h4>
									<p class="card-text">{{ doctor.address|safe }}</p>
									{% if doctor.schedule %}
										<a href="/doctor/{{ doctor.pk }}" class="btn btn-primary">View this doctor</a>
									{% else %}
										<p>This doctor has no schedule, sorry</p>
									{% endif %}
								</div>
							</div>
						{% endfor %}
						{% if not category.doctor_set.all %}
							<h3>There are no doctors in this category yet</h3>
						{% endif %}
					</div>
				{% endfor %}
				{% if not categories %}
					<h3>No categories were added</h3>
				{% endif %}
			</div>
		</div>
	</div>

{% endblock base %}

templates/footer.html
<footer class="page-footer font-small blue pt-4">
	<div class="container-fluid text-center text-md-left">
		<div class="row">
			<div class="col-md-6 mt-md-0 mt-3">
				<h5 class="text-uppercase">APPointment</h5>
				<p>Simple app to make appointments to doctors</p>
			</div>
			<hr class="clearfix w-100 d-md-none pb-3">
			<div class="col-md-3 mb-md-0 mb-3">
				<h5 class="text-uppercase">Author: Zolotarev Mikhail</h5>
				<ul class="list-unstyled">
					<li>
						<a href="https://github.com/Zoitom">GitHub</a>
					</li>
					<li>
						<a href="https://gitlab.com/Zoitom">GitLab</a>
					</li>
					<li>
						<a href="https://linkedin.com/in/zoitom">LinkedIn</a>
					</li>
				</ul>
			</div>
			</div>
		</div>
	</div>
</footer>

templates/header.html
<header>

</header>

templates/my_appointments.html
{% extends 'base_container.html' %}

{% block base_container %}
	{% if deactivated %}
		<div class="alert alert-danger" role="alert">
		  An appointment was deactivated
		</div>
	{% endif %}
{% if appointments %}
	<ul>
		{% for appointment in appointments %}
			{% if appointment.is_active %}
				{% if user.client %}
				<li class="m-2"> There is an appointment to {{ appointment.doctor.user.first_name }} {{ appointment.doctor.user.last_name }} at {{ appointment.datetime }} </li>
				{% else %}
				<li class="m-2"> There is an appointment from {{ appointment.client.user.first_name }} {{ appointment.client.user.last_name }} at {{ appointment.datetime }}</li>
				{% endif %}
				<form method="GET">
					<input type="hidden" name="appointment-id" value="{{ appointment.id }}"/>
					<button type="submit" class="btn btn-primary mb-4">Deactivate</button>
				</form>
			{% endif %}
		{% endfor %}
	</ul>
{% else %}
<h2>You have no appointments</h2>
{% endif %}
{% endblock base_container %}

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="collapsingNavbar">
        <ul class="navbar-nav">
            <li class="nav-item {% if 'browse' in request.path %}active{% endif %}">
                <a class="nav-link text-nowrap" href="/browse">Browse</a>
            </li>
            <li class="nav-item {% if 'my_appointments' in request.path %}active{% endif %}">
                <a class="nav-link text-nowrap" href="/my_appointments">My Appointments</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-nowrap" href="">Logged in as: {{ user.get_username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-nowrap" href="/profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-nowrap" href="/accounts/logout">Log out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-nowrap" href="/admin">CRUD Panel</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link text-nowrap" href="/accounts/login">Log in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-nowrap" href="/accounts/register">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/profile.html
{% extends 'base_container.html' %}

{% block base_container %}
<div class="row m-4">

    <div class="col-12 col-md-4">
        {% load static %}
        <img src="{% static 'doctors/profile_picture.png' %}" class="rounded" alt="icon_profile_picture">
    </div>

    <div class="col-md-8">
        <dl class="row">
            {% if user.doctor %}

            {% endif %}
            <dt class="col-sm-3">Name</dt>
            <dd class="col-sm-9">
                {{ user.first_name }} {{ user.last_name }}
                <button class="btn btn-primary btn-sm ml-3" type="button" data-toggle="collapse" data-target="#collapseNameForm" aria-expanded="false" aria-controls="collapseNameForm">
                    Change
                </button>
                <div class="collapse my-1" id="collapseNameForm">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="First name" name="firstname" required>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Last name" name="lastname" required>
                            </div>
                            <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                        </div>
                    </form>
                </div>
            </dd>

            <dt class="col-sm-3">Username</dt>
            <dd class="col-sm-9">{{ user.username }}</dd>

            <dt class="col-sm-3">E-mail</dt>
            <dd class="col-sm-9">{{ user.email }}</dd>

            <dt class="col-sm-3">Password</dt>
            <dd class="col-sm-9">
                <a class="btn btn-primary btn-sm" href="/accounts/password_change">Change password</a>
            </dd>

            {% if user.doctor %}
            <dt class="col-sm-3">Address</dt>
            <dd class="col-sm-9">
                {{ user.doctor.address}}
                <button class="btn btn-primary btn-sm ml-3" type="button" data-toggle="collapse" data-target="#collapseAddressForm" aria-expanded="false" aria-controls="collapseAddressForm">
                    Change
                </button>
                <div class="collapse my-1" id="collapseAddressForm">
                    <form method="POST">
                        {% csrf_token %}
                        <input type="text" class="form-control" value="{{ user.doctor.address }}" name="address" required>
                        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    </form>
                </div>
            </dd>

            <dt class="col-sm-3">Categories</dt>
            <dd class="col-sm-9">
                {% if user.doctor.categories.count %}
                <ul>
                {% for category in user.doctor.categories.all %}
                    <li>{{ category.name }}</li>
                {% endfor %}
                </ul>
                <a href="/admin/doctors/doctor/{{ user.doctor.id }}/change/" class="btn btn-primary btn-sm ml-3">Change categories</a>

                {% else %}
                    You haven't added any category yet
                    <a href="/admin/doctors/doctor/{{ user.doctor.id }}/change/" class="btn btn-primary btn-sm ml-3">Add categories</a>
                {% endif %}
            </dd>

            <dt class="col-sm-3">Schedule</dt>
            <dd class="col-sm-9">
                {% if user.doctor.schedule %}
                <!-- schedule table-->
                    <p class="card-text">Interval: {{ user.doctor.schedule.interval }} minutes</p>
                    <div class="table-responsive">
                        <table class="table table-stripped table-sm">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Day of week</th>
                                    <th>From</th>
                                    <th>To</th>
                                </tr>
                            </thead>
                            <tr>
                                <th>Monday</th>
                                <td>{{ user.doctor.schedule.monday_from }}</td>
                                <td>{{ user.doctor.schedule.monday_to }}</td>
                            </tr>
                            <tr>
                                <th>Tuesday</th>
                                <td>{{ user.doctor.schedule.tuesday_from }}</td>
                                <td>{{ user.doctor.schedule.tuesday_to }}</td>
                            </tr>
                            <tr>
                                <th>Wednesday</th>
                                <td>{{ user.doctor.schedule.wednesday_from }}</td>
                                <td>{{ user.doctor.schedule.wednesday_to }}</td>
                            </tr>
                            <tr>
                                <th>Thursday</th>
                                <td>{{ user.doctor.schedule.thursday_from }}</td>
                                <td>{{ user.doctor.schedule.thursday_to }}</td>
                            </tr>
                            <tr>
                                <th>Friday</th>
                                <td>{{ user.doctor.schedule.friday_from }}</td>
                                <td>{{ user.doctor.schedule.friday_to }}</td>
                            </tr>
                            <tr>
                                <th>Saturday</th>
                                <td>{{ user.doctor.schedule.saturday_from }}</td>
                                <td>{{ user.doctor.schedule.saturday_to }}</td>
                            </tr>
                        </table>
                    </div>
                <a href="/admin/doctors/schedule/{{ user.doctor.schedule.id }}/change/" class="btn btn-primary btn-sm ml-3">Change Schedule</a>
                {% else %}
                    You have no schedule yet
                    <a href="/admin/doctors/schedule/add" class="btn btn-primary btn-sm ml-3">Create Schedule</a>
                {% endif %}
            </dd>
            {% endif %}
        </dl>
    </div>
</div>
{% endblock base_container %}

templates/root.html
{% extends 'base_container.html' %}

{% block base_container %}
<div class="jumbotron">
	<h1 class="display-4">APPointment</h1>
	<p class="lead">Simple app to make appointments to doctors</p>
</div>

<div class="row">
	<div class="col text-right">
		<h2>{{ numcat }} categories</h2>
		<h2>{{ numdoc }} doctors</h2>
		<h2>{{ numapp }} appointments made</h2>
		<h2 class="mt-2">Join us</h2>
	</div>

	<div class="col">
		{% load static %}
		<img src="{% static 'doctors/stock_doctor.jpg' %}" class="mx-auto rounded" alt="stock_doctor_image" height="318">
	</div>

</div>		

{% endblock base_container %}

templates/timetable.html
{% extends 'base_container.html' %}

{% block base_container %}
<h2>{{ doctor.user.first_name }} {{ doctor.user.last_name }}</h2>
<h3>{{ doctor.address|safe }}

{% if authorization_exception %}
<div class="alert alert-danger" role="alert">
	You are not logged in as a client! Register or log in as a client to make appointments!
</div>
<a href="/accounts/login" class="btn btn-primary">Okay</a>
{% else %}

<h3>Schedule</h3>
<!-- schedule table-->
<div>
	<p class="card-text">Interval: {{ doctor.schedule.interval }} minutes</p>
	<table class="table">
		<thead>
			<tr>
				<td>Monday</td>
				<td>Tuesday</td>
				<td>Wednesday</td>
				<td>Thursday</td>
				<td>Friday</td>
				<td>Saturday</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>{{ doctor.schedule.monday_from }} - {{ doctor.schedule.monday_to }}</td>
				<td>{{ doctor.schedule.tuesday_from }} - {{ doctor.schedule.tuesday_to }}</td>
				<td>{{ doctor.schedule.wednesday_from }} - {{ doctor.schedule.wednesday_to }}</td>
				<td>{{ doctor.schedule.thursday_from }} - {{ doctor.schedule.thursday_to }}</td>
				<td>{{ doctor.schedule.friday_from }} - {{ doctor.schedule.friday_to }}</td>
				<td>{{ doctor.schedule.saturday_from }} - {{ doctor.schedule.saturday_to }}</td>
			</tr>
	</table>
</div>
<div class="d-flex justify-content-center">
	<form method="POST">
		{% csrf_token %}
		<button class="btn btn-primary m-2" name="week" type="submit" value="{{ week|add:-1 }}">
			Previous week
		</button>
<!--			todo: change to date format-->
		Week number: {{ week }}
		<button class="btn btn-primary m-2" name="week" type="submit" value="{{ week|add:1 }}">
			Next week
		</button>
	</form>
</div>
<table class="table table-sm">
	<thead class="thead-dark">
		<tr>
			<th scope="col">Time</th>
			<th scope="col" style="width: 16%">Monday</th>
			<th scope="col" style="width: 16%">Tuesday</th>
			<th scope="col" style="width: 16%">Wednesday</th>
			<th scope="col" style="width: 16%">Thursday</th>
			<th scope="col" style="width: 16%">Friday</th>
			<th scope="col" style="width: 16%">Saturday</th>
		</tr>
	</thead>
	<tbody>
		{% for time, window_days in timetable.items %}
			<tr>
				<th scope="row">{{ time }}</th>
				{% for window in window_days %}
					{% if window == "free" %}
						<td class="table-success text-center">
							<form method="POST">
								{% csrf_token %}
								<input type="hidden" name="appointment-week" value="{{ week }}"/>
								<input type="hidden" name="appointment-weekday" value="{{ forloop.counter0 }}"/>
								<input type="hidden" name="appointment-time" value="{{ time }}"/>
								<input type="hidden" name="appointment-doctor" value="{{ doctor.pk }}"/>
								<button type="submit" class="btn btn-success btn-block btn-sm">Book</button>
							</form>
						</td>
					{% elif window == "busy" %}
						<td class="table-danger text-center">Already booked</td>
					{% else %}
						<td class="table-secondary text-center">Not available</td>
					{% endif %}
				{% endfor %}
			</tr>
		{% endfor %}
	</tbody>
</table>

{% endif %}
{% endblock base_container %}

templates/welcome.html
{% extends 'base_container.html' %}

{% block base_container %}

<h2>Your registration is completed</h2>
{% if request.user.doctor %}
<p>But you are not done yet! You have to set up your schedule, add address and categories, which will help the clients to find you</p>
<p>Go to Profile page where you add and change your data</p>
{% else %}
<p>Use navigation menu to browse doctors or modify your profile</p>
<p>After you make your first appointment it will appear on My Appointments page</p>
{% endif %}
<p>If you would like to remove your account, please contact our administrator by e-mail, which you can found at the bottom of the page</p>
<div>
	{% load static %}
	<img src="{% static 'doctors/stock_doctor_2.jpg' %}" class="mx-auto rounded" alt="stock_doctor_image" height="318">
</div>

{% endblock base_container %}